[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
did_doc_updater = "Eaz8J2hJGzFJYSX6reZittxrFkL6PdESB5AJt7LvAUsd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/a7/.config/solana/custom-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
