version: '3.8'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs  # To persist IPFS data
    restart: unless-stopped

volumes:
  ipfs-data:
